<div class="row">
	<hr>
	<h1 class="col-sm-12">
		Add New House
		<a href="<?php echo $this->url('house'); ?>" class="btn btn-success pull-right">
			<span class="glyphicon glyphicon-chevron-left"></span>
			Back
		</a>
	</h1>
	<hr>
</div>

<?php echo $this->form()->openTag($this->form); ?>

<div class="form-group">
	<label for="name" class="col-sm-2 control-label">Name <?php echo $this->required(); ?></label>
	<div class="col-sm-3">
		<?php echo $this->formInput($this->form->get('name')); ?>
	</div>
</div>

<div class="form-group">
	<label for="name" class="col-sm-2 control-label">Image</label>
	<div class="col-sm-4">
		<?php echo $this->formFile($this->form->get('image')); ?>
		<div class="help-block">500x300px</div>
	</div>
</div>

<div class="form-group">
	<label for="name" class="col-sm-2 control-label">Icon</label>
	<div class="col-sm-4">
		<?php echo $this->formFile($this->form->get('icon')); ?>
		<div class="help-block">100x100px</div>
	</div>
</div>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-2">
		<?php echo $this->formSubmit($this->form->get('submit')); ?>
	</div>
</div>

<?php echo $this->form()->closeTag(); ?>
