<div class="row">
	<hr>
		<h1 class="col-sm-12">
			Houses
			<a href="<?php echo $this->url('house/add'); ?>" class="btn btn-success pull-right">Add New House</a>
		</h1>
	<hr>
</div>
<div class="row">
	<table class="table dataTable" id="house-table">
		<thead>
			<tr>
				<th width="1">id</th>
				<th>Name</th>
				<th width="15%">Functions</th>
			</tr>
		</thead>
		<tbody>
		<?php
			if ($this->data->count()) {
				/** @var \Vinyl\Entity\House $row */
				foreach ($this->data as $row) {
		?>
			<tr>
				<td><?php echo $row->getId(); ?></td>
				<td><?php echo $row->getName(); ?></td>
				<td>
					<a href="<?php echo $this->url('house/edit', ['id' => $row->getId()]); ?>" class="label label-success">Edit</a>
					<span class="text-muted">/</span>
					<a href="<?php echo $this->url('house/delete', ['id' => $row->getId()]); ?>" class="label label-danger">Delete</a>
				</td>
			</tr>
		<?php
				}
			} else {
		?>
			<tr>
				<td>No Data</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
		<?php
			}
		?>
		</tbody>
	</table>
</div>
