<div class="row">
	<hr>
	<h1 class="col-sm-12">
		<?php echo \Vinyl\Constant\DBData::getTherapy($this->form->get('therapy_id')->getValue()); ?>
		<a href="<?php echo $this->url('therapy'); ?>" class="btn btn-success pull-right">
			<span class="glyphicon glyphicon-chevron-left"></span>
			Back
		</a>
	</h1>
	<hr>
</div>

<?php echo $this->form()->openTag($this->form); ?>

<div class="form-group">
	<label for="name" class="col-sm-2 control-label">Therapy</label>
	<div class="col-sm-3">
		<?php echo $this->formSelect($this->form->get('therapy_id')); ?>
	</div>
</div>

<div class="form-group">
	<label for="birthday" class="col-sm-2 control-label">Date From <?php echo $this->required(); ?></label>
	<div class="col-sm-2">
		<?php echo $this->formInput($this->form->get('date_from')); ?>
	</div>
</div>

<div class="form-group">
	<label for="region" class="col-sm-2 control-label">Date To <?php echo $this->required(); ?></label>
	<div class="col-sm-2">
		<?php echo $this->formInput($this->form->get('date_to')); ?>
	</div>
</div>

<div class="form-group">
	<label for="description" class="col-sm-2 control-label">Description</label>
	<div class="col-sm-10">
		<?php echo $this->formTextarea($this->form->get('description')); ?>
	</div>
</div>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-2">
		<?php echo $this->formSubmit($this->form->get('submit')); ?>
	</div>
</div>

<?php echo $this->form()->closeTag(); ?>
