<div class="row">
	<hr>
	<h1 class="col-sm-12">
		Add New Fence
		<a href="<?php echo $this->url('fence'); ?>" class="btn btn-success pull-right">
			<span class="glyphicon glyphicon-chevron-left"></span>
			Back
		</a>
	</h1>
	<hr>
</div>

<?php if ($this->available) { ?>
	<?php if ($this->error) { ?>
	<div class="alert alert-danger">
		<strong>Oh snap!</strong>
		<p>There was an error!</p>
	</div>
	<?php } ?>

	<?php echo $this->form()->openTag($this->form); ?>

<div class="form-group">
	<label for="name" class="col-sm-2 control-label">Name <?php echo $this->required(); ?></label>
	<div class="col-sm-3">
		<?php echo $this->formInput($this->form->get('name')); ?>
	</div>
</div>

<div class="form-group">
	<label for="category_id" class="col-sm-2 control-label">Category <?php echo $this->required(); ?></label>
	<div class="col-sm-3">
		<?php echo $this->formSelect($this->form->get('category_id')); ?>
	</div>
</div>

<div class="form-group">
	<label for="name" class="col-sm-2 control-label">Image</label>
	<div class="col-sm-4">
		<?php echo $this->formFile($this->form->get('image')); ?>
	</div>
</div>

<div class="form-group">
	<label for="name" class="col-sm-2 control-label">Icon</label>
	<div class="col-sm-4">
		<?php echo $this->formFile($this->form->get('icon')); ?>
		<div class="help-block">60x40px</div>
	</div>
</div>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-2">
		<?php echo $this->formSubmit($this->form->get('submit')); ?>
	</div>
</div>

	<?php echo $this->form()->closeTag(); ?>
<?php } else { ?>
<div class="alert alert-danger">
	<strong>Oh snap!</strong>
	<p>You need to add category first. <a href="<?php echo $this->url('category/add'); ?>" class="alert-link">Follow to white rabbit</a>.</p>
</div>
<?php } ?>
