<div class="row">
	<hr>
	<h1 class="col-sm-12">
		<?php echo $this->form->get('name')->getValue(); ?>
		<a href="<?php echo $this->url('fence'); ?>" class="btn btn-success pull-right">
			<span class="glyphicon glyphicon-chevron-left"></span>
			Back
		</a>
	</h1>
	<hr>
</div>

<?php if ($this->error) { ?> <?php \Zend\Debug\Debug::dump($this->error); ?>
	<div class="alert alert-danger">
		<strong>Oh snap!</strong>
		<p>There was an error!</p>
	</div>
<?php } ?>

<?php echo $this->form()->openTag($this->form); ?>

<div class="form-group">
	<label for="name" class="col-sm-2 control-label">Name <?php echo $this->required(); ?></label>
	<div class="col-sm-3">
		<?php echo $this->formInput($this->form->get('name')); ?>
	</div>
</div>

<div class="form-group">
	<label for="category_id" class="col-sm-2 control-label">Category <?php echo $this->required(); ?></label>
	<div class="col-sm-3">
		<?php echo $this->formSelect($this->form->get('category_id')); ?>
	</div>
</div>

<div class="form-group">
	<label for="name" class="col-sm-2 control-label">Image <?php echo $this->required(); ?></label>
	<div class="col-sm-4">
		<?php echo $this->formFile($this->form->get('image')); ?>
	</div>
</div>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-3">
		<img src="<?php echo BASE_DIR; ?>/upload/fence/<?php echo $this->id; ?>/big.png?sh<?php echo mt_rand(1000000, 9999999); ?>" class="thumbnail" height="100">
	</div>
</div>

<div class="form-group">
	<label for="name" class="col-sm-2 control-label">Icon <?php echo $this->required(); ?></label>
	<div class="col-sm-4">
		<?php echo $this->formFile($this->form->get('icon')); ?>
	</div>
</div>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-3">
		<img src="<?php echo BASE_DIR; ?>/upload/fence/<?php echo $this->id; ?>/icon.png?sh<?php echo mt_rand(1000000, 9999999); ?>" class="thumbnail">
	</div>
</div>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-2">
		<?php echo $this->formSubmit($this->form->get('submit')); ?>
	</div>
</div>

<?php echo $this->form()->closeTag(); ?>
