<div class="row">
	<hr>
		<h1 class="col-sm-12">
			Fences
			<a href="<?php echo $this->url('fence/add'); ?>" class="btn btn-success pull-right">Add New Fence</a>
		</h1>
	<hr>
</div>
<div class="row">
	<table class="table dataTable" id="fence-table">
		<thead>
			<tr>
				<th width="1">id</th>
				<th width="1">Icon</th>
				<th>Name</th>
				<th>Category</th>
				<th width="15%">Functions</th>
			</tr>
		</thead>
		<tbody>
		<?php
			if ($this->data->count()) {
				/** @var \Vinyl\Entity\Fence $row */
				foreach ($this->data as $row) {
		?>
			<tr>
				<td><?php echo $row->getId(); ?></td>
				<td><img src="<?php echo HOST . 'upload/fence/' . $row->getId() . '/icon.png'; ?>?sh<?php echo mt_rand(1000000, 9999999); ?>" class="fence-preview orange"></td>
				<td><?php echo $row->getName(); ?></td>
				<td><?php echo $row->getCategory(); ?></td>
				<td>
					<a href="<?php echo $this->url('fence/edit', ['id' => $row->getId()]); ?>" class="label label-success">Edit</a>
					<span class="text-muted">/</span>
					<a href="<?php echo $this->url('fence/delete', ['id' => $row->getId()]); ?>" class="label label-danger">Delete</a>
				</td>
			</tr>
		<?php
				}
			} else {
		?>
			<tr>
				<td>No Data</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
		<?php
			}
		?>
		</tbody>
	</table>
</div>
