<style scoped="scoped">
	body {
		margin: 0;
		padding: 0;
	}
	iframe {
		position: fixed;
		top: 0;
		left: 0;
		bottom: 0;
		right: 0;
		max-width: 768px;
		width: 100%;
		height: 100%;
		border: none;
		margin: 0 auto;
		padding: 0;
		overflow: hidden;
		z-index: 999999;
	}
</style>
<script>
	$(function() {
		if ($(window).width() < 768) {
			window.location.href = '/app.html';
		}
	});
</script>
<iframe src="/intro.html?v=1.2" id="iframe"></iframe>
