<div class="page-header">
	<h1>Dashboard <small>All in one place</small></h1>
</div>
<div class="row">
	<div class="col-sm-12">Soon...</div>
	<!--<div class="col-sm-4">
		<div class="well widget text-primary">
			250 <small class="title">children</small>
		</div>
	</div>
	<div class="col-sm-4">
		<div class="well widget text-primary">
			31 <small class="title">therapies</small>
		</div>
	</div>
	<div class="col-sm-4">
		<div class="well widget text-danger">
			5 <small class="title">not involved</small>
		</div>
	</div>
	<div class="col-sm-8">
		<div class="well widget text-primary">
			1253
			<span class="widget-additional">
				<span class="text-muted">/</span>
				<span class="text-success">1226</span>
				<span class="text-muted">/</span>
				<span class="text-warning">23</span>
				<span class="text-muted">/</span>
				<span class="text-danger">5</span>
			</span>
			<small class="title">attendance (all / partly / never)</small>
		</div>
	</div>
	<div class="col-sm-4">
		<div class="well widget text-success">
			<sup><i class="widget-additional glyphicon glyphicon-arrow-up"></i></sup>13<span class="widget-additional text-muted">%</span>
			<small class="title">depends on last month</small>
		</div>
	</div>

	<div class="col-sm-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					Last Therapy
					<small class="text-info">
						<i class="glyphicon glyphicon-info-sign pull-right" data-toggle="popover" data-original-title="Description" data-content="You can find longest Description text here"></i>
					</small>
				</h3>
			</div>
			<div class="panel-body text-">
				<strong>RACECOURCE</strong>
				<span class="pull-right text-muted">DEC 2 - DEC 15</span>
			</div>

			<table class="table table-striped">
				<thead>
					<tr>
						<th>Child</th>
						<th>Status</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><a href="#">Baxshyan Eduard</a></td>
						<td><span class="label label-success pull-right">full</span></td>
					</tr>
					<tr>
						<td><a href="#">Engibaryan Artyom</a></td>
						<td><span class="label label-success pull-right">full</span></td>
					</tr>
					<tr>
						<td><a href="#">Israyelyan Gagik</a></td>
						<td><span class="label label-warning pull-right">partly</span></td>
					</tr>
					<tr>
						<td><a href="#">Manukyan Vazgen</a></td>
						<td><span class="label label-danger pull-right">never</span></td>
					</tr>
					<tr>
						<td><a href="#">Vardanyan Razmik</a></td>
						<td><span class="label label-success pull-right">full</span></td>
					</tr>
					<tr>
						<td><a href="#">Gugushikyan Gugush</a></td>
						<td><span class="label label-success pull-right">full</span></td>
					</tr>
					<tr>
						<td><a href="#">Barseghyan Mushegh</a></td>
						<td><span class="label label-warning pull-right">partly</span></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="col-sm-8">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					Last Added 5 Children
				</h3>
			</div>

			<table class="table table-striped">
				<thead>
					<tr>
						<th>Child</th>
						<th>Parent</th>
						<th>Diseas</th>
						<th>Functions</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Vardanyan Razmik</td>
						<td>Nina Pina China</td>
						<td>hivandutyun #1</td>
						<td>
							<a href="/child/view/3" class="label label-success">View</a>
							<span class="text-muted">/</span>
							<a href="/child/edit/3" class="label label-success">Edit</a>
							<span class="text-muted">/</span>
							<a href="/child/delete/3" class="label label-danger">Delete</a>
						</td>
					</tr>
					<tr>
						<td>Gugushikyan Gugush</td>
						<td>Nina Pina China</td>
						<td>hivandutyun #1</td>
						<td>
							<a href="/child/view/7" class="label label-success">View</a>
							<span class="text-muted">/</span>
							<a href="/child/edit/7" class="label label-success">Edit</a>
							<span class="text-muted">/</span>
							<a href="/child/delete/7" class="label label-danger">Delete</a>
						</td>
					</tr>
					<tr>
						<td>Gabrielyan Eduard</td>
						<td>Aram Charam</td>
						<td>hivandutyun #2</td>
						<td>
							<a href="/child/view/2" class="label label-success">View</a>
							<span class="text-muted">/</span>
							<a href="/child/edit/2" class="label label-success">Edit</a>
							<span class="text-muted">/</span>
							<a href="/child/delete/2" class="label label-danger">Delete</a>
						</td>
					</tr>
					<tr>
						<td>Israyelyan Umut</td>
						<td>Aram Charam</td>
						<td>hivandutyun #2</td>
						<td>
							<a href="/child/view/6" class="label label-success">View</a>
							<span class="text-muted">/</span>
							<a href="/child/edit/6" class="label label-success">Edit</a>
							<span class="text-muted">/</span>
							<a href="/child/delete/6" class="label label-danger">Delete</a>
						</td>
					</tr>
					<tr>
						<td>Barseghyan Mushegh</td>
						<td>Davit Avetikyan</td>
						<td>hivandutyun #2</td>
						<td>
							<a href="/child/view/4" class="label label-success">View</a>
							<span class="text-muted">/</span>
							<a href="/child/edit/4" class="label label-success">Edit</a>
							<span class="text-muted">/</span>
							<a href="/child/delete/4" class="label label-danger">Delete</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>-->
</div>
