<div class="row">
	<hr>
		<h1 class="col-sm-12">
			Parents

			<?php if ($this->hasRole(\Haymayrer\Constant\Permission::PARENT_ADD)) { ?>
			<a href="<?php echo $this->url('parent-add'); ?>" class="btn btn-success pull-right">Add New Parent</a>
			<?php } ?>
		</h1>
	<hr>
</div>
<div class="row">
	<table id="parents-table">
		<thead>
			<tr>
				<th width="20%">Full Name</th>
				<th width="15%">Birthday</th>
				<th width="20%">Region</th>
				<th width="15%">Phone</th>
				<th width="15%">Functions</th>
			</tr>
		</thead>
		<tbody>
		<?php
			if ($this->data) {
				/** @var \Haymayrer\Entity\Parents $row */
				foreach ($this->data as $row) {
		?>
			<tr>
				<td><?php echo $row->getName(); ?></td>
				<td><?php echo $row->getBirthday(); ?></td>
				<td><?php echo \Haymayrer\Constant\DBData::getRegion($row->getRegion()); ?></td>
				<td><?php echo $row->getPhone(); ?></td>
				<td>
					<a href="<?php echo $this->url('parent-view', ['id' => $row->getId()]); ?>" class="label label-success">View</a>

					<?php if ($this->hasRole(\Haymayrer\Constant\Permission::PARENT_EDIT)) { ?>
					<span class="text-muted">/</span>
					<a href="<?php echo $this->url('parent-edit', ['id' => $row->getId()]); ?>" class="label label-success">Edit</a>
					<?php } ?>

					<?php if ($this->hasRole(\Haymayrer\Constant\Permission::PARENT_DELETE)) { ?>
					<span class="text-muted">/</span>
					<a href="<?php echo $this->url('parent-delete', ['id' => $row->getId()]); ?>" class="label label-danger">Delete</a>
					<?php } ?>
				</td>
			</tr>
		<?php
				}
			}
		?>
		</tbody>
	</table>
</div>
