<?php

/**
 * @var $data \Haymayrer\Entity\Parents
 * @var $children \Haymayrer\Entity\Child[]|\ArrayObject
 */
$data = $this->data;
$children = $this->children;

if ($data) {

?>
<div class="row">
	<hr>
	<h1 class="col-sm-12">
		<?php echo $data->getName(); ?>
		<a href="<?php echo $this->url('parent'); ?>" class="btn btn-success pull-right">
			<span class="glyphicon glyphicon-chevron-left"></span>
			Back
		</a>
	</h1>
	<hr>
</div>
<div class="col-sm-8 col-sm-offset-2">
	<table class="table table-bordered table-hover">
		<tbody>
			<tr class="active">
				<td>Name</td>
				<td><?php echo htmlspecialchars($data->getName()); ?></td>
			</tr>
			<tr>
				<td>Children</td>
				<td>
					<ul class="list-inline null">
						<?php if ($children->count()) { ?>
						<?php foreach ($children as $child) { ?>
						<li><a href="<?php echo $this->url('child-view', ['id' => $child->getId()]); ?>"><?php echo $child->getName(); ?></a></li>
						<?php } ?>
						<?php } ?>
					</ul>
				</td>
			</tr>
			<tr class="active">
				<td>Birthday</td>
				<td><?php echo $data->getBirthday(); ?></td>
			</tr>
			<tr class="active">
				<td>Phone Number</td>
				<td>+374 <?php echo $data->getPhone(); ?></td>
			</tr>
			<tr>
				<td>Phone Number (Alternative)</td>
				<td>+374 <?php echo $data->getPhoneAlternative(); ?></td>
			</tr>
			<tr>
				<td>Region</td>
				<td><?php echo \Haymayrer\Constant\DBData::getRegion($data->getRegion()); ?></td>
			</tr>
			<tr>
				<td>District</td>
				<td><?php echo \Haymayrer\Constant\DBData::getDistrict($data->getDistrict()); ?></td>
			</tr>
			<tr>
				<td>Address</td>
				<td><?php echo htmlspecialchars($data->getAddress()); ?></td>
			</tr>
			<tr>
				<td>Residence Address</td>
				<td><?php echo htmlspecialchars($data->getAddressResidence()); ?></td>
			</tr>
			<tr>
				<td>Registration Date</td>
				<td><?php echo $data->getTimestamp(); ?></td>
			</tr>
			<tr>
				<td>Single Mother</td>
				<td><?php echo ($data->getSingleMother() ? '<span class="label label-danger">Yes</span>' : '<span class="label label-default">No</span>'); ?></td>
			</tr>
			<tr>
				<td>Family In Need</td>
				<td><?php echo ($data->getInNeed() ? '<span class="label label-danger">Yes</span>' : '<span class="label label-default">No</span>'); ?></td>
			</tr>
			<tr>
				<td>Description</td>
				<td><?php echo htmlspecialchars($data->getDescription()); ?></td>
			</tr>
		</tbody>
	</table>
</div>
<?php

} else {

?>
<div class="alert alert-danger alert-dismissable">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	<strong>Warning!</strong> Requested parent not found.
</div>
<?php

}

?>
