<?php

/**
 * @var $data \Vinyl\Entity\Child
 */
$data = $this->data;

if ($data) {

?>
<div class="row">
	<hr>
	<h1 class="col-sm-12">
		<?php echo $data->getName(); ?>
		<a href="<?php echo $this->url('child'); ?>" class="btn btn-success pull-right">
			<span class="glyphicon glyphicon-chevron-left"></span>
			Back
		</a>
	</h1>
	<hr>
</div>
<div class="col-sm-8 col-sm-offset-2">
	<table class="table table-bordered table-hover">
		<tbody>
			<tr class="active">
				<td>Name</td>
				<td><?php echo $data->getName(); ?></td>
			</tr>
			<tr class="active">
				<td>Parent</td>
				<td>
					<?php if ($this->hasRole(\Vinyl\Constant\Permission::PARENT_VIEW)) { ?>
					<a href="<?php echo $this->url('parent-view', ['id' => $data->getParentId()]); ?>"><?php echo $data->getParentName(); ?></a>
					<?php } else { ?>
					<?php echo $data->getParentName(); ?>
					<?php } ?>
				</td>
			</tr>
			<tr>
				<td>Birthday</td>
				<td><?php echo $data->getBirthday(); ?></td>
			</tr>
			<tr>
				<td>Disease</td>
				<td><?php echo \Vinyl\Constant\DBData::getDisease($data->getDisease()); ?></td>
			</tr>
			<tr>
				<td>Registration Date</td>
				<td><?php echo $data->getTimestamp(); ?></td>
			</tr>
			<tr>
				<td>Description</td>
				<td><?php echo htmlspecialchars($data->getDescription()); ?></td>
			</tr>
		</tbody>
	</table>
</div>
<?php

} else {

?>
<div class="alert alert-danger alert-dismissable">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	<strong>Warning!</strong> Requested child not found.
</div>
<?php

}

?>
